# Generated by Django 2.2.7 on 2019-11-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
