# Generated by Django 2.2.7 on 2019-11-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191129_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
