# Generated by Django 2.2.7 on 2019-11-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_post_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
